### ISSUE TITLE
Ingestion dependency not found when starting Core server locally (CONTRIBUTING.md)

### ISSUE THREAD

**Issue by NicholaiStaalung** [gojek/feast#294]
## Expected Behavior 
The Feast Core server should start

## Current Behavior
[ERROR] Failed to execute goal on project feast-core: Could not resolve dependencies for project feast:feast-core:jar:0.3.0-SNAPSHOT: Could not find artifact feast:feast-ingestion:jar:0.3.0-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project feast-core: Could not resolve dependencies for project feast:feast-core:jar:0.3.0-SNAPSHOT: Could not find artifact feast:feast-ingestion:jar:0.3.0-SNAPSHOT

## Steps to reproduce
git clone -b 0.3-dev https://github.com/gojek/feast
cd feast/core
mvn spring-boot:run

### Specifications

- Version: Feast 0.3-dev
- Platform: Localhost
- Subsystem: Java 8, Maven 3.6, Python 3.6.8, Postgress, Redis, Kafka

## Possible Solution
Add dependency artifact at location described in core/pow.xml or change the setup process to pulle the ingestion artifact before starting the Core server

**Comment by woop** [comment]
Thanks a lot of creating this issue! 

We're moving quite quickly at the moment and making a lot of changes. For now, all `mvn` builds should happen from the project root, so the `CONTRIBUTING.md` file is now out of date.

An example is here: https://github.com/gojek/feast/blob/0.3-dev/.prow/scripts/test-core-ingestion.sh. The same command works for packaging.

Will leave this issue open until we update the `CONTRIBUTING.md`

Once we merge in the latest charts (#289), then you should be able to use the following instructions to get up and running locally on Minikube: https://github.com/gojek/feast/blob/0.3-dev/docs/getting-started/install-feast.md

**Comment by NicholaiStaalung** [comment]
> Thanks a lot of creating this issue!
> 
> We're moving quite quickly at the moment and making a lot of changes. For now, all `mvn` builds should happen from the project root, so the `CONTRIBUTING.md` file is now out of date.
> 
> An example is here: https://github.com/gojek/feast/blob/0.3-dev/.prow/scripts/test-core-ingestion.sh. The same command works for packaging.
> 
> Will leave this issue open until we update the `CONTRIBUTING.md`
> 
> Once we merge in the latest charts (#289), then you should be able to use the following instructions to get up and running locally on Minikube: https://github.com/gojek/feast/blob/0.3-dev/docs/getting-started/install-feast.md

Super. Will wait for the update. Thanks

**Comment by ches** [comment]
If you'd like to assign this to me, I should have `CONTRIBUTING.md` updates coming along with #272 (hopefully tomorrow).

**Comment by woop** [comment]
Yea, that would be great!

**Comment by woop** [comment]
@NicholaiStaalung I believe this is resolved. Please let me know if it isn't and I will reopen the issue.

**Comment by gbaludev** [comment]
I am still getting this error. Moreover all the URL given above are returning 404

**Comment by woop** [comment]
> I am still getting this error. Moreover all the URL given above are returning 404

This exception is over a year old. Can you please provide the exact version and stack trace that you are receiving @gbaludev?

**Comment by gbaludev** [comment]
mvn package -X -Dmaven.test.skip=true  complied successfully

**Comment by gbaludev** [comment]
Reactor Summary for Feast 0.9.0-SNAPSHOT:
[INFO] 
[INFO] Feast .............................................. SUCCESS [  5.395 s]
[INFO] Feast Data Types for Java .......................... SUCCESS [ 29.726 s]
[INFO] Feast Common ....................................... SUCCESS [ 18.238 s]
[INFO] Feast Storage API .................................. SUCCESS [  4.236 s]
[INFO] Feast Storage Connectors ........................... SUCCESS [  0.579 s]
[INFO] Feast Storage Connector for Redis .................. SUCCESS [  3.855 s]
[INFO] Feast Common Test .................................. SUCCESS [  4.507 s]
[INFO] Feast Core ......................................... SUCCESS [  7.698 s]
[INFO] Feast Serving ...................................... SUCCESS [  5.444 s]
[INFO] Feast SDK for Java ................................. SUCCESS [  3.776 s]
[INFO] Feast Coverage Java ................................ SUCCESS [  1.834 s]
[INFO] Feast Spark Ingestion .............................. SUCCESS [03:40 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:07 min
[INFO] Finished at: 2020-12-03T21:35:53+05:30

**Comment by gbaludev** [comment]
Running setup.py develop for feast
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
libcst 0.3.15 requires pyyaml>=5.2, but you have pyyaml 5.1.2 which is incompatible.

**Comment by gbaludev** [comment]
Took a fresh repository clone, works finr. Feast 0.9.0-SNAPSHOT
